- hosts: ids-snort
  become_method: sudo
  become: yes
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
    home_dir: "/home/vagrant"
  roles:
    - snort
- hosts: ids-suricata
  become_method: sudo
  become: yes
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
    home_dir: "/home/vagrant"
  roles:
    - suricata

- hosts: ids-zeek
  become_method: sudo
  become: yes
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
    home_dir: "/home/vagrant"
  roles:
    - zeek

- hosts: all
  become_method: sudo
  become: yes
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
    home_dir: "/home/vagrant"
  roles:
    - docker