- name: Install docker dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
        - apt-transport-https 
        - ca-certificates 
        - curl 
        - gnupg-agent 
        - software-properties-common
        - python3
        - python3-pip

- name: Add docker repo keys
  shell:
    cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: Add stable repo
  shell:
    cmd: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

- name: Install docker
  apt:
    name: "{{ packages }}"
  vars:
    packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io

- name: Install docker-py
  pip:
    name: 
      - docker-py
      - docker-compose

- name: Start docker compose
  shell:
    cmd: docker-compose up -d
    chdir: /home/vagrant/docker_compose
