- name: Install suricata repo
  apt_repository:
    repo: ppa:oisf/suricata-stable
    state: present
- name: Run apt-get update
  apt:
    update_cache: yes
- name: Get Suricata with debugging enabled
  apt:
    name: suricata-dbg
